version: "3"
services:
    redis:
        container_name: redis-ru102js
        image: redis:5
        ports:
            - "6379:6379"

    redis-commander:
        container_name: redis-commander-ru102js
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        links:
            - redis
        environment:
        - REDIS_HOSTS=local:redis:6379
        ports:
        - "8081:8081"

    app-ru102js:
        container_name: app-ru102js
        build:
            context: .
            dockerfile: Dockerfile.dev
        depends_on: 
            - redis
        links:
            - redis
        ports:
            - "8888:8888"
